# Generated by Django 5.1.6 on 2025-03-08 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatmessage',
            name='detection',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterModelOptions(
            name='threatmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='threatmessage',
            name='threat_detected',
        ),
        migrations.AddField(
            model_name='threatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 8, 20, 40, 46, 355441)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatmessage',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threatmessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
