# Generated by Django 5.1.6 on 2025-03-09 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_remove_threatmessage_detection_delete_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatmessage',
            options={'verbose_name': 'Threat Message', 'verbose_name_plural': 'Threat Messages'},
        ),
        migrations.RemoveField(
            model_name='threatmessage',
            name='details',
        ),
        migrations.AddField(
            model_name='threatmessage',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threatmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
