# Generated by Django 5.1.6 on 2025-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alter_threatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatmessage',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
