# Generated by Django 5.1.6 on 2025-03-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatmessage',
            name='detection',
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_label', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='detection_d_timesta_ddfa6a_idx'), models.Index(fields=['class_label'], name='detection_d_class_l_f65076_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='ThreatMessage',
        ),
    ]
