# Generated by Django 5.1.6 on 2025-03-11 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_detectedobject_y1_detectedobject_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedobject',
            name='user',
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='y1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
