# """
# Django settings for GODSEYE project.

# Generated by 'django-admin startproject' using Django 5.1.4.
# """

# import os
# from pathlib import Path
# from dotenv import load_dotenv

# # Load environment variables from .env file
# load_dotenv()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback-secret-key")

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # Set to False in production

# ALLOWED_HOSTS = ["*"]  # Change this in production to specific domains

# # Application definition
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'authentication',
#     'detection',
#     'history',
#     'alert',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'GODSEYE.urls'

# import os
# from pathlib import Path

# BASE_DIR = Path(__file__).resolve().parent.parent

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],  # Must include this
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'GODSEYE.wsgi.application'

# # Database Configuration
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# # Password validation
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]

# # Internationalization
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'Asia/Kolkata'
# USE_I18N = True
# USE_TZ = True

# # Static files (CSS, JavaScript, Images)
# STATIC_URL = 'static/'

# # Set STATICFILES_DIRS only if the directory exists
# if os.path.exists(BASE_DIR / 'static'):
#     STATICFILES_DIRS = [BASE_DIR / 'static']

# # Authentication Configuration
# AUTHENTICATION_BACKENDS = [
#     'authentication.backend.EmailBackend',  # Custom backend for email/username login
#     'django.contrib.auth.backends.ModelBackend',  # Default Django backend
# ]

# # Custom User Model
# AUTH_USER_MODEL = 'authentication.CustomUser'

# # Default primary key field type
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # Login & Logout Redirects
# LOGIN_URL = '/auth/login/'
# LOGIN_REDIRECT_URL = '/auth/user/'
# LOGOUT_REDIRECT_URL = '/auth/login/'

# # Session Expiry
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_AGE = 1800  # 30 minutes

# # Disable caching
# CACHE_MIDDLEWARE_SECONDS = 0
# CACHE_MIDDLEWARE_KEY_PREFIX = 'site_cache'
# #EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "eabeljohn453@gmail.com"
# EMAIL_HOST_PASSWORD = "gmst bkwz xluo yklh"
# # settings.py
# TWILIO_ACCOUNT_SID = 'AC6628e1220cbb931abaf03a6d5fde33fb'
# TWILIO_AUTH_TOKEN = '085480c3208ae6a7b673955353e9fc54'
# TWILIO_PHONE_NUMBER = '+18102168936'  # e.g., '+1234567890'
# EMERGENCY_CONTACT_NUMBERS = ['+917736951636']  # List of admin phone numbers to call